# Docker-compose for local dev environment
services:
  mongo-vertical-template:
    image: mongo:4.4.8
    restart: always
    command: [ "--replSet", "my-replica-set", "--bind_ip_all", "--port", "30002" ]
    volumes:
      - ./data/mongo-vertical-template:/data/db
    ports:
      - 30002:30002
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'my-replica-set',members:[{_id:0,host:\"localhost:30002\"}]}).ok || rs.status().ok" | mongo --port 30002 --quiet) -eq 1
      interval: 10s
      start_period: 30s
