/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("kotlin.vertical.test.kotlin-application-conventions")
}

dependencies {
}

application {
    // Define the main class for the application.
    mainClass.set("kotlin.vertical.test.app.AppKt")
}
